MAIN_KEY = "main:app"
EMPTY_STRING = ""

STATUS_CODE_KEY = "status_code"
DETAIL_MESSAGE_KEY = "detail_message"
ERROR_RESPONSE_DETAIL_KEY = "detail"
AUTHORIZATION_KEY = "Authorization"


HTTP_200_OK = 200
HTTP_201_CREATED = 201
HTTP_401_UNAUTHORIZED = 401
HTTP_403_FORBIDDEN = 403
HTTP_404_NOT_FOUND = 404
HTTP_409_CONFLICT = 409

IMAGE_BASE_FOLDER = "images"

READ_BINARY_MODE = "rb"
WRITE_BINARY_MODE = "wb"

IMAGE_PNG_CONTENT_TYPE = "image/png"
