MAIN_KEY = "main:app"
EMPTY_STRING = ""

STATUS_CODE_KEY = "status_code"
DETAIL_MESSAGE_KEY = "detail_message"
ERROR_RESPONSE_DETAIL_KEY = "detail"

HTTP_200_OK = 200
HTTP_401_UNAUTHORIZED = 401
HTTP_404_NOT_FOUND = 404
HTTP_409_CONFLICT = 409