HOST_ENV_VARIABLE_KEY = "HOST"
HOST_DEFAULT = "localhost"

PORT_ENV_VARIABLE_KEY = "PORT"
PORT_DEFAULT = 8000

WELCOM_MESSAGE_ENV_VARIABLE_KEY = "WELCOME_MESSAGE"

DATABASE_URI_ENV_VARIABLE_KEY = "DATABASE_URI"
DATABASE_URI_DEFAULT = "sqlite:///sqlite.db"

TEST_DATABASE_URI_ENV_VARIABLE_KEY = "TEST_DATABASE_URI"
TEST_DATABASE_URI_DEFAULT = "sqlite:///test.db"