ROOT_ROUTE = "/"

USER_BASE_ROUTE = "/users"
USER_TAG = "users"

USER_REGISTER_ROUTE = "/register"
USER_REGISTER_FULL_ROUTE = f"{USER_BASE_ROUTE}{USER_REGISTER_ROUTE}"

USER_LOGIN_ROUTE = "/login"
USER_LOGIN_FULL_ROUTE = f"{USER_BASE_ROUTE}{USER_LOGIN_ROUTE}"

USER_CHANGE_DESCRIPTION_ROUTE = "/description"
USER_CHANGE_DESCRIPION_FULL_ROUTE = f"{USER_BASE_ROUTE}{USER_CHANGE_DESCRIPTION_ROUTE}"