ROOT_ROUTE = "/"
USER_BASE_ROUTE = "/users"
USER_TAG = "users"

USER_REGISTER_ROUTE = "/register"
USER_REGISTER_FULL_ROUTE = f"{USER_BASE_ROUTE}{USER_REGISTER_ROUTE}"

USER_LOGIN_ROUTE = "/login"
USER_LOGIN_FULL_ROUTE = f"{USER_BASE_ROUTE}{USER_LOGIN_ROUTE}"

USER_CHANGE_DESCRIPTION_ROUTE = "/description"
USER_CHANGE_DESCRIPION_FULL_ROUTE = f"{USER_BASE_ROUTE}{USER_CHANGE_DESCRIPTION_ROUTE}"

USER_UPLOAD_IMAGE_ROUTE = '/upload-user-image'
USER_UPLOAD_IMAGE_FULL_ROUTE = f"{USER_BASE_ROUTE}{USER_UPLOAD_IMAGE_ROUTE}"

USER_GET_IMAGE_ROUTE = '/image'
USER_GET_IMAGE_FULL_ROUTE = f'{USER_BASE_ROUTE}{USER_GET_IMAGE_ROUTE}'

TASK_PREFIX = "/tasks"

TASK_CREATE_ROUTE = "/"
TASK_CREATE_FULL_ROUTE = f"{TASK_PREFIX}{TASK_CREATE_ROUTE}"
