from constants.database.task import (
    TASK_DESCRIPTION_KEY,
    TASK_NAME_KEY, 
    TASK_PLANNED_DATE_KEY
)


FIRST_TASK_TASK_NAME = "First Task"
FIRST_TASK_TASK_DESCRIPTION = "This is the first task"
FIRST_TASK_TASK_PLANNED_DATE = "2020-01-01"

FIRST_TASK = {
    TASK_NAME_KEY: FIRST_TASK_TASK_NAME,
    TASK_DESCRIPTION_KEY: FIRST_TASK_TASK_DESCRIPTION,
    TASK_PLANNED_DATE_KEY: FIRST_TASK_TASK_PLANNED_DATE,
}