from constants.database.task import (
    TASK_COMPLETE_KEY,
    TASK_COMPLETED_TIME_KEY,
    TASK_DESCRIPTION_KEY,
    TASK_ID_KEY,
    TASK_NAME_KEY,
    TASK_PLANNED_DATE_KEY
)


FIRST_TASK_TASK_ID = 1
FIRST_TASK_TASK_NAME = "First Task"
FIRST_TASK_TASK_DESCRIPTION = "This is the first task"
FIRST_TASK_TASK_PLANNED_DATE = "2020-01-01"
FIRST_TASK_COMPLETED_TIME = "2020-01-01 00:00:00"

FIRST_TASK_CHANGE_TASK_NAME = "First Task Changed"
FIRST_TASK_CHANGE_TASK_DESCRIPTION = "This is the first task changed"
FIRST_TASK_CHANGE_TASK_PLANNED_DATE = "2020-01-02"

FIRST_TASK = {
    TASK_ID_KEY: FIRST_TASK_TASK_ID,
    TASK_NAME_KEY: FIRST_TASK_TASK_NAME,
    TASK_DESCRIPTION_KEY: FIRST_TASK_TASK_DESCRIPTION,
    TASK_PLANNED_DATE_KEY: FIRST_TASK_TASK_PLANNED_DATE,
}

FIRST_TASK_COMPLETE = dict(
    **FIRST_TASK,
    **{
        TASK_COMPLETE_KEY: True,
        TASK_COMPLETED_TIME_KEY: FIRST_TASK_COMPLETED_TIME,
    }
)

FIRST_TASK_CHANGED_TASK_NAME_TASK = dict(
    **{
        TASK_ID_KEY: FIRST_TASK_TASK_ID,
        TASK_DESCRIPTION_KEY: FIRST_TASK_TASK_DESCRIPTION,
        TASK_PLANNED_DATE_KEY: FIRST_TASK_TASK_PLANNED_DATE,
    },
    **{
        TASK_NAME_KEY: FIRST_TASK_CHANGE_TASK_NAME,
    }
)


FIRST_TASK_CHANGE_TASK_DESCRIPTION_TASK = {
    TASK_ID_KEY: FIRST_TASK_TASK_ID,
    TASK_NAME_KEY: FIRST_TASK_TASK_NAME,
    TASK_PLANNED_DATE_KEY: FIRST_TASK_TASK_PLANNED_DATE,
    TASK_DESCRIPTION_KEY: FIRST_TASK_CHANGE_TASK_DESCRIPTION,
}

FIRST_TASK_CHANGE_TASK_PLANNED_DATE_TASK = {
    TASK_ID_KEY: FIRST_TASK_TASK_ID,
    TASK_NAME_KEY: FIRST_TASK_TASK_NAME,
    TASK_DESCRIPTION_KEY: FIRST_TASK_TASK_DESCRIPTION,
    TASK_PLANNED_DATE_KEY: FIRST_TASK_CHANGE_TASK_PLANNED_DATE,
}
