MAIN_KEY = "main:app"

HOST_ENV_VARIABLE_KEY = "HOST"
PORT_ENV_VARIABLE_KEY = "PORT"
WELCOM_MESSAGE_ENV_VARIABLE_KEY = "WELCOME_MESSAGE"
DATABASE_URI_ENV_VARIABLE_KEY = "DATABASE_URI"

HOST_DEFAULT = "localhost"
PORT_DEFAULT = 8000


EMPTY_STRING = ""

ROOT_ROUTE = "/"

USER_BASE_ROUTE = "/users"
USER_REGISTER_ROUTE = f"{USER_BASE_ROUTE}/register"

DATABASE_URI_DEFAULT = "sqlite:///sqlite.db"

USER_TABLE_NAME = "users"
USERNAME_MAX_LENGTH = 30
PASSWORD_MAX_LENGTH = 50
USER_DESCRIPTION_MAX_LENGTH = 200
IMAGE_PATH_MAX_LENGTH = 100

USERNAME_KEY = "username"
PASSWORD_KEY = "password"

TASK_TABLE_NAME = "tasks"
TASK_NAME_MAX_LENGTH = 30
TASK_DESCRIPTION_MAX_LENGTH = 200

HTTP_200_OK = 200
