MAIN_KEY = "main:app"

# the variable key of .env file
HOST_ENV_VARIABLE_KEY = "HOST"
PORT_ENV_VARIABLE_KEY = "PORT"
WELCOM_MESSAGE_ENV_VARIABLE_KEY = "WELCOME_MESSAGE"
DATABASE_URI_ENV_VARIABLE_KEY = "DATABASE_URI"
TEST_DATABASE_URI_ENV_VARIABLE_KEY = "TEST_DATABASE_URI"

HOST_DEFAULT = "localhost"
PORT_DEFAULT = 8000


EMPTY_STRING = ""

ROOT_ROUTE = "/"

USER_BASE_ROUTE = "/users"

USER_REGISTER_ROUTE = "/register"
USER_REGISTER_FULL_ROUTE = f"{USER_BASE_ROUTE}{USER_REGISTER_ROUTE}"

USER_LOGIN_ROUTE = "/login"
USER_LOGIN_FULL_ROUTE = f"{USER_BASE_ROUTE}{USER_LOGIN_ROUTE}"

DATABASE_URI_DEFAULT = "sqlite:///sqlite.db"
TEST_DATABASE_URI_DEFAULT = "sqlite:///test.db"

USER_TABLE_NAME = "users"
USERNAME_MAX_LENGTH = 30
PASSWORD_MAX_LENGTH = 50
USER_DESCRIPTION_MAX_LENGTH = 200
IMAGE_PATH_MAX_LENGTH = 100

USERNAME_KEY = "username"
PASSWORD_KEY = "password"

TASK_TABLE_NAME = "tasks"
TASK_NAME_MAX_LENGTH = 30
TASK_DESCRIPTION_MAX_LENGTH = 200


STATUS_CODE_KEY = "status_code"
DETAIL_MESSAGE_KEY = "detail_message"

HTTP_200_OK = 200
HTTP_409_CONFLICT = 409
HTTP_404_NOT_FOUND = 404

OK_STATUS = {
    STATUS_CODE_KEY: HTTP_200_OK,
    DETAIL_MESSAGE_KEY: None
}

USERNAME_EXISTS_MESSAGE = "Username exists."
USERNAME_EXIST_STATUS = {
    STATUS_CODE_KEY: HTTP_409_CONFLICT,
    DETAIL_MESSAGE_KEY: USERNAME_EXISTS_MESSAGE,
}

USERNAME_DOES_NOT_EXIST_MESSAGE = "Username does not exist."
USERNAME_DOES_NOT_EXIST_STATUS = {
    STATUS_CODE_KEY: HTTP_404_NOT_FOUND,
    DETAIL_MESSAGE_KEY: USERNAME_DOES_NOT_EXIST_MESSAGE,
}