TASK_TABLE_NAME = "tasks"
TASK_NAME_MAX_LENGTH = 30
TASK_DESCRIPTION_MAX_LENGTH = 200


TASK_NAME_KEY = "taskName"
TASK_DESCRIPTION_KEY = "taskDescription"
TASK_PLANNED_DATE_KEY = "plannedDate"

FIRST_TASK_TASK_NAME = "First Task"
FIRST_TASK_TASK_DESCRIPTION = "This is the first task"
FIRST_TASK_TASK_PLANNED_DATE = "2020-01-01"

FIRST_TASK = {
    TASK_NAME_KEY: FIRST_TASK_TASK_NAME,
    TASK_DESCRIPTION_KEY: FIRST_TASK_TASK_DESCRIPTION,
    TASK_PLANNED_DATE_KEY: FIRST_TASK_TASK_PLANNED_DATE,
}