USER_TABLE_NAME = "users"
USERNAME_MAX_LENGTH = 30
PASSWORD_MAX_LENGTH = 50
USER_DESCRIPTION_MAX_LENGTH = 200
IMAGE_PATH_MAX_LENGTH = 100

USERNAME_KEY = "username"
PASSWORD_KEY = "password"
USER_KEY = "user"
TOKEN_KEY = "token"
USERID_KEY = "userId"
USER_DESCRIPTION_KEY = "description"
USER_USERID_KEY = "userId"
USER_IMAGE_KEY = 'userImage'

IMAGE_FOLDER = "images"
